parameters:
    auth.header.email: '%env(AUTH_HEADER_EMAIL)%'
    auth.header.roles: '%env(AUTH_HEADER_ROLES)%'
    jwks_url: '%env(resolve:JWKS_URL)%'
    jwt_skip_verify: '%env(bool:JWT_SKIP_VERIFY)%'

    # the id is not a class, so it won't be used for autowiring
    # app.rot13.transformer:
    #     class: App\Util\Rot13Transformer
    #     # ...

    # # but this fixes it!
    # # the "app.rot13.transformer" service will be injected when
    # # an App\Util\Rot13Transformer type-hint is detected
    # App\Util\Rot13Transformer: '@app.rot13.transformer'

services:
    beerfranz_servicebundle.security_header_authenticator:
        class: Beerfranz\ServiceBundle\Security\HeaderAuthenticator
        arguments: 
            - '@Doctrine\ORM\EntityManagerInterface'
            - '@Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface'
            - '@Symfony\Contracts\Cache\TagAwareCacheInterface'
            - '@App\Repository\UserRepository'
    Beerfranz\ServiceBundle\Security\HeaderAuthenticator: '@beerfranz_servicebundle.security_header_authenticator'

    beerfranz_servicebundle.security_jwt_authenticator:
        class: Beerfranz\ServiceBundle\Security\JwtAuthenticator
        arguments: 
            - '@Doctrine\ORM\EntityManagerInterface'
            - '@Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface'
            - '@Symfony\Contracts\Cache\TagAwareCacheInterface'
            - '@App\Repository\UserRepository'
    Beerfranz\ServiceBundle\Security\JwtAuthenticator: '@beerfranz_servicebundle.security_jwt_authenticator'
